
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: book_loans
    columns:
      - name: borrow_date
        tests:
          - not_null
          - expression_is_true:
              expression: "user_id > 0"
              fail_calc: "count(*)"
              error_if: "count(*) > 0"
              where: "user_id is not null"
